### ISSUE TITLE
Latest change to action.yml contains secrets.GITHUB_TOKEN which results in errors

### ISSUE THREAD

**Issue by JamesAMater** [databricks/run-notebook#35]
The Latest change that was published has introduced a bug that results in the job erroring and not starting . There is a Github secret in the description for pr-comment-github-token in action.yml and in that description there is "${{secrets.GITHUB_TOKEN}}" so when this is used in an actual workflow its trying to render the value of  ${{secrets.GITHUB_TOKEN}}. I have attached a couple of screenshots showing the error and the update to action.yml

![image](https://user-images.githubusercontent.com/108788574/207167918-bd6ad770-15c4-49bb-8ff9-d2eea8dbe408.png)

![image](https://user-images.githubusercontent.com/108788574/207168439-fb3cf80a-0e11-4d3d-95e4-09b2c042ef0e.png)

**Comment by mohamad-arabi** [comment]
Weird, Let me fix that. I didn't get that issue when I was testing it manually. Thanks for filing this

**Comment by mohamad-arabi** [comment]
fixed in #36
